title: CV | Gabriel Eguia
description:  Gabriel Eguia's CV.
url: https://gabrieleguia.github.io
baseurl: '/gme-jekyll-cv'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
